---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
  - name: updating repositories
    shell: 
      cmd: yum update -y
   
  - name: installing  nginx
    yum:
      name: nginx 
      state: present

  - name: restart nginx
    service: 
      name: nginx
      state: restarted
